[package]
name = "remotex-control"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
remotex-crypto.workspace = true
remotex-protocol.workspace = true
tokio.workspace = true

[lints]
workspace = true

