[package]
name = "remotex-control-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reqwest.workspace = true

[dev-dependencies]
tokio.workspace = true
serde_json.workspace = true

[lints]
workspace = true
