[package]
name = "remotex-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
bincode.workspace = true
bytes.workspace = true
hex.workspace = true
quinn.workspace = true
remotex-crypto.workspace = true
remotex-protocol.workspace = true
remotex-transport.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
tauri = "2.9.3"
tokio.workspace = true
tracing.workspace = true

[build-dependencies]
tauri-build = "2.5.2"

[lints]
workspace = true
