[package]
name = "remotex-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
hex.workspace = true
quinn.workspace = true
rand.workspace = true
reqwest.workspace = true
remotex-capture.workspace = true
remotex-clipboard.workspace = true
remotex-crypto.workspace = true
remotex-file-transfer.workspace = true
remotex-input.workspace = true
remotex-protocol.workspace = true
remotex-transport.workspace = true
remotex-video.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
